# Generated by Django 5.0.4 on 2024-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_order_customer_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
