# Generated by Django 5.0.4 on 2024-12-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_budget_alter_customer_customer_name_and_more'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(blank=True, choices=[('INFO', 'Info'), ('ERROR', 'Error'), ('WARNING', 'Warning')], default='INFO', max_length=10, null=True),
        ),
    ]
